services:
  hive-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASEURL=${NEXT_PUBLIC_BASEURL}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    restart: unless-stopped
    ports:
      - '11231:3000'
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - API_BASE_URL=${API_BASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_BASEURL=${NEXT_PUBLIC_BASEURL}
    networks:
      - hive
      - coolify
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=coolify'
      - 'traefik.http.routers.hive-root-https.rule=Host(`hive.uguru.dev`)'
      - 'traefik.http.routers.hive-root-https.entryPoints=https'
      - 'traefik.http.routers.hive-root-https.tls=true'
      - 'traefik.http.routers.hive-root-https.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.hive-root-https.service=hive-service'
      - 'traefik.http.routers.hive-wildcard-https.rule=HostRegexp(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?\.hive\.uguru\.dev$`)'
      - 'traefik.http.routers.hive-wildcard-https.entryPoints=https'
      - 'traefik.http.routers.hive-wildcard-https.tls=true'
      - 'traefik.http.routers.hive-wildcard-https.tls.certresolver=letsencrypt-dns'
      - 'traefik.http.routers.hive-wildcard-https.tls.domains[0].main=*.hive.uguru.dev'
      - 'traefik.http.routers.hive-wildcard-https.service=hive-service'
      - 'traefik.http.routers.hive-root-http.rule=Host(`hive.uguru.dev`)'
      - 'traefik.http.routers.hive-root-http.entryPoints=http'
      - 'traefik.http.routers.hive-root-http.middlewares=hive-redirect'
      - 'traefik.http.routers.hive-wildcard-http.rule=HostRegexp(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?\.hive\.uguru\.dev$`)'
      - 'traefik.http.routers.hive-wildcard-http.entryPoints=http'
      - 'traefik.http.routers.hive-wildcard-http.middlewares=hive-redirect'
      - 'traefik.http.middlewares.hive-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.hive-redirect.redirectscheme.permanent=true'
      - 'traefik.http.services.hive-service.loadbalancer.server.port=3000'

networks:
  hive:
    external: true
  coolify:
    external: true